import { DEVICE_WIDTH } from './Screen';

export const PIZZA_CONTAINER_WIDTH = (60 / 100) * DEVICE_WIDTH;
export const TWENTY_PER_OF_SC_WIDTH = (20 / 100) * DEVICE_WIDTH;
export const SIXTYEIGHT_PER_OF_SC_WIDTH = (68 / 100) * DEVICE_WIDTH;
export const SIXTYFIVE_PER_OF_SC_WIDTH = (65 / 100) * DEVICE_WIDTH;
export const SEVENTY_PER_OF_SC_WIDTH = (70 / 100) * DEVICE_WIDTH;
export const EIGHTY_PER_OF_SC_WIDTH = (80 / 100) * DEVICE_WIDTH;
export const PARTICLE_HEIGHT_WIDTH = 20;
